language: python
python:
  - "2.7"
  - "3.3"
install:
  - "pip install simplejson pystache --use-mirrors"
script: "python buildsite.py"
notifications:
  irc:
    channels:
      - "chat.freenode.net#qtox"
    template: "%{repository} (%{commit}): %{message} Build: %{build_url} / Changes: %{compare_url}"
